collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3052277
color:
  saturation: 0.3625676
  brandStrength: 0.3285136
  rhythmicContrast: 0.7183811
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.1163575
layout_spectrum: 0.9932547
name: 'Audio Juice '
