layout_spectrum: 0.1558227
typography_spectrum: 0.3052277
color:
  saturation: 0.3625676
  brandStrength: 0.3285136
  lightness: 0.1163575
  rhythmicContrast: 0.7183811
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: 'Audio Juice '
